### ISSUE TITLE
Planar versus great circle distance

### ISSUE THREAD

**Issue by alexanderbrenning** [mlr-org/mlr3spatiotempcv#128] opened 2021-05-06 13:51 UTC
When using spatial object with unprojected CRS (i.e. lat/lon), does mlr3spatiotempcv use great circle distance (on the ellipsoid) or Euclidean distances based on lat/lon values? Is this handled consistently across resampling tools, e.g. buffering and clustering?
This should be clarified in the paper, but perhaps it should be turned into a feature request...

**Comment by pat-s** [comment] 2021-05-08 12:27
This depends on the underlying methods and is not controlled by {mlr3spatiotempcv}.

The only (re)projection done by {mlr3spatiotempcv} is when plotting and no CRS was given. Then by default WGS84 is used (of which I heard lately that it might be a bad default choice).

I am not sure if {mlr3spatiotempcv} should provide an option to handle projection related issues in a general sense since that might result in different results than using the underlying packages directly.
If there are issues in underlying methods I think patching them upstream would be benefitial.

**Comment by pat-s** [comment] 2021-05-08 12:57
Reading your paragraph on this again, I think that {mlr3spatiotempcv} should not have a strong opinion/correction on projection handling - at least not more than the upstream packages do.

If certain underlying non-spatial buffering/clustering methods are struggling with certain projection types, I believe these should be handled upstream.
Given that \pkg{mlr3spatiotempcv} invokes upstream package functions if they are lightweight, these fixes would populate through.

For some though, \pkg{mlr3spatiotempcv} applies a more lightweight implementation and some manual fixes might be needed.

I am not aware of any issues related to projection types though - do you have some concrete in mind?

**Comment by pat-s** [comment] 2021-05-13 09:11
After some more internal conversations it seems I might have misunderstood the OP.

I currently see two issues:

- The effect of the CRS on buffering/clustering during resampling
- The effect of the CRS in `autoplot()`

I'll open two distinct issues.

**Comment by pat-s** [comment] 2021-05-13 09:43
@alexanderbrenning 

AFAICS only `spcv_buffer` uses a spatial buffering via `sf::st_distance()` (see also #130) and the use of great circle/euclidean depends on whether an unprojected/projected CRS was supplied when creating the task.

Would you suggest to 

- convert non-spatial clustering/buffering methods (i.e. the ones from {sperrorest}) to spatial ones? I.e. make use of a spatial clustering method instead of clustering on numerics (= coordinates). 
- enforce the use of a projected/unprojected CRS for buffering in `spcv_buffer`?
- something different?

**Comment by pat-s** [comment] 2021-05-22 13:06
For unprojected CRS, I've found that the python library `spacv` uses [haversine](https://www.geeksforgeeks.org/haversine-formula-to-find-distance-between-two-points-on-a-sphere/) to calculate the distance.

**Comment by alexanderbrenning** [comment] 2021-05-28 12:59
Looking at some of the mlr3spatioempcv code, I now understand why you blame ;-) it on upstream packages. Nevertheless, I believe that the user of mlr3spatiotempcv expects that the different partitioning strategies in mlr3spatiotempcv behave consistently. It's not really a seamless integration if the users have to find out for themselves if the underlying sperrorest, blockCV, CAST, or native implementation (1) completely ignores projections, (2) accounts for projections, (3) accounts for projections but only in some cases, ...
There's probably no short-term solution, therefore I'd suggest that the help files should state very clearly if and how projections (and distances) are handled, and in the paper we can state that the package is striving to homogenize this.

**Comment by pat-s** [comment] 2021-05-29 10:45
> Nevertheless, I believe that the user of mlr3spatiotempcv expects that the different partitioning strategies in mlr3spatiotempcv behave consistently.

Partly yes but I am not sure if this is really a common expectation.
{mlr3spatiotempcv} does not claim to "fix" any problematic things in the upstream packages. The idea is provide an easy and consistent interface to access all the methods - not judging their quality (in whatever way).
The use of euclidean/great circle distances in all of the methods might even be desired.

> and in the paper we can state that the package is striving to homogenize this.

I think I understand that from a users perspective it would be great if all methods would follow one principle here. But I am still not convinced that mlr3spatiotempcv should add opinionated fixed on top of the methods to account for this. Why? I think this might raise confusion what is actually happening behind the scenes and what "method" is finally used. For example, buffering:

- buffering from {blockCV}?
- buffering from {sperrorest}?
- buffering from {blockCV} via {mlr3spatiotempcv} with its adjustment for projection?
- etc.

There are many abstraction layers which we already outline in the table listing the methods.
Any "added feature" on top of methods by {mlr3spatiotempcv} would be another then.

Maybe I see it wrong though - open for discussion.

**Comment by pat-s** [comment] 2021-06-27 12:06
Looking at this after some weeks, I still think it's difficult and I am not sure that {mlr3spatiotempcv} should apply/offer any heuristic to handle this.

Some methods do not make use of any projection, some do and for those which do, it depends on which CRS was handed over in the data supplied (e.g. in a `sf` object).

It might be easy to implement for some and more difficult for others. 
However, it would also require to re-implement almost all methods given that for some {mlr3spatiotempcv} just passes down the respective objects to the upstream functions.

Feel free to reply even if the issue is closed and thanks for bringing up this topic!

**Closed by pat-s** 2021-06-27 12:06 UTC
Labels: Priority: Low, Type: Question
